### ISSUE TITLE
Если  загружать две картинки в двух полях одновременно, то во второе поле загружается первая

### ISSUE THREAD

**Issue by SlimSavernake** [mohorev/yii2-upload-behavior#36]
Если  загружать две картинки в двух полях одновременно, то во второе поле загружается первая картинка. Получается две одинаковых. Что не так делаю?

**Comment by greg-repo** [comment]
`
<div class="row">
                <div class="col-sm-12">
                    <?= $form->field( $machine, 'img_src',['options' => ['class' => 'hidden']])->fileInput(['accept' => 'image/*', 'id' => 'upload-machine-photo'])->label(false); ?>
                    <?= $form->field( $machine, 'lyt_src',['options' => ['class' => 'hidden']])->fileInput(['accept' => 'image/*', 'id' => 'upload-machine-layout'])->label(false); ?>
                    <div class="row layout-row">
                        <div class="col-sm-12 layout">
                            <div class="row">
                                <?= Html::img(
                                    $machine->getBehavior('upload-layout-behavior')->getThumbUploadUrl('lyt_src', 'preview'), [
                                        'class' => 'img-thumbnail',
                                        'data-trigger-click' => '#upload-machine-layout'
                                    ]
                                ) ?>
                            </div>
                        </div>
                        <div class="col-sm-4 col-md-offset-4 image-preview text-center">
                            <?= Html::img(
                                $machine->getBehavior('upload-image-behavior')->getThumbUploadUrl('img_src', 'preview'), [
                                    'class' => 'img-thumbnail',
                                    'data-trigger-click' => '#upload-machine-photo'
                                ]
                            ) ?>
                        </div>
                    </div>
                    <div class="row">
                        <?= $form->field($machine, 'name', ['options' => ['class' => 'col-sm-6']])->textInput(['placeholder' => 'Pick up a name for your machine']); ?>
                        <?= $form->field($machine, 'status', ['options' => ['class' => 'col-sm-6']])->dropDownList(
                            UserMachine::getStatusesList(), ['prompt' => '--- Select your machine status ---']
                        ); ?>
                    </div>
                </div>
            </div>
`

Попробуй получать через поведение
