### ISSUE TITLE
Своя библиотека для generateImageThumb

### ISSUE THREAD

**Issue by loveorigami** [mohorev/yii2-upload-behavior#37]
Хочу использовать для манипуляции с изображениями другую библиотеку, вместо Imagine.

Прошу сделать публичным метод generateImageThumb
https://github.com/mohorev/yii2-upload-behavior/blob/master/UploadImageBehavior.php#L231

чтоб можно было его переопределить в моем наследуемом классе.

**Comment by mohorev** [comment]
`generateImageThumb` является **protected**
его и так можно переопределить в наследуемом классе

**Comment by loveorigami** [comment]
Действительно, запамятовал малость. 
Спасибо.
