### ISSUE TITLE
Как получить exif информацию?

### ISSUE THREAD

**Issue by SlimSavernake** [mohorev/yii2-upload-behavior#41]

**Comment by mohorev** [comment]
Данное поведение умеет только загружать файлы.

Для того чтобы получить EXIF - обратитесь к документации `yii2-imagine` или `imagine`

https://github.com/yiisoft/yii2-imagine
https://github.com/avalanche123/Imagine

Или к другим сторонним библиотекам, например http://php.net/manual/ru/imagick.getimageproperties.php
