### ISSUE TITLE
Conflict because of yii2-imagine version

### ISSUE THREAD

**Issue by cronfy** [mohorev/yii2-upload-behavior#44]
In my project there is `yiisoft/yii2-imagine: "^2.1"` requirement. It uses features from 2.1 version and can't work with 2.0.

But mohorev/yii2-upload-behavior requires `"yiisoft/yii2-imagine": "~2.0.0"`.

So, I can't install both: composer reports conflict.

Is there any way to drop `yiisoft/yii2-imagine` dependency for those who does not use thumbnails?

**Comment by mohorev** [comment]
Fixed in https://github.com/mohorev/yii2-upload-behavior/issues/46
