### ISSUE TITLE
Undefined class constant 'COLOR_OPACITY'

### ISSUE THREAD

**Issue by sokolnikov911** [mohorev/yii2-upload-behavior#46]
Got error `Undefined class constant 'COLOR_OPACITY'`
in library https://github.com/avalanche123/Imagine which used in yiisoft/yii2-imagine. 

I think you need use more fresh version of yiisoft/yii2-imagine.

**Comment by mohorev** [comment]
Привет. Данное поведение писалось как то очень давно когда еще я работал с yii2, но сейчас поддерживать его нету возможности. 

@sokolnikov911 может ты можешь сделать пуллреквест?
А то я уже несколько лет не работаю с yii2 и данное расширение не использую.

Еще похожая проблема была в https://github.com/mohorev/yii2-upload-behavior/issues/44

@cronfy или у тебя есть идеи? А то у меня правда нету времени этим заняться)

**Comment by cronfy** [comment]
@mohorev Я думаю, нужно просто убрать  из composer.json этот `require yiisoft/yii2-imagine`. Кто пользуется иконками - поставит, кто нет - тому мешать не будет.

**Comment by mohorev** [comment]
@cronfy мне кажется большинство пользуется изменением размеров загруженных картинок, а чем не вариант обновить версию `yiisoft/yii2-imagine`: `^2.1` и выпустить новый релиз? Как предложил @sokolnikov911 ?
Так по идее мы ничего не сломаем у тех, у кого установлена старая версия поведения, а остальные обновятся до последней версии `yii2-imagine`. Тебя это устроит?

**Comment by cronfy** [comment]
@mohorev да, если выпустить новый релиз, то у тех, кто использует текущую версию, ничего не сломается. Для меня - если зависимость от yii2-imagine останется в том или ином виде - не важно, каким именно способом это будет сделано. Меня бы устроило, если бы этой зависимости не было. Мне не очень понятно, зачем в UploadBehavior вообще есть работа с превьюшками картинок, когда загружать можно и документы, и архивы, к которым превьюшки не сделаешь. Я для превью предпочитаю использовать специализированный инструмент, например, glide, а UploadBehavior - только для загрузки.

**Comment by mohorev** [comment]
@cronfy тогда есть вариант исключить `yii2-imagine` из обязательной зависимости.
Вынести ее в `suggest` композера. https://getcomposer.org/doc/04-schema.md#suggest
А в UploadImageBehavior в конструкторе проверить что `yii2-imagine` установлен (на `class_exists` например), иначе бросить исключение.

Тогда те, кто использует расширение для загрузки только файлов не будут тащить эту зависимость, а кому нужны превью должны будут у себя в проекте явно указать ее.

**Comment by cronfy** [comment]
@mohorev Да, логично. Я могу сделать PR на выходных, надо?

**Comment by mohorev** [comment]
@cronfy Ага, было бы супер!

**Comment by mohorev** [comment]
https://github.com/mohorev/yii2-upload-behavior/pull/47

**Comment by mohorev** [comment]
UPD: Еще переименовал название репозитория, т.к. никнейм я сменил уже давно - а до этого руки не доходили.

**Comment by cronfy** [comment]
@mohorev да, все работает как надо.

**Comment by mohorev** [comment]
@cronfy Отлично, новый тег https://github.com/mohorev/yii2-upload-behavior/releases/tag/0.1.8
Спасибо за помощь! Задачи закрываю.
