### ISSUE TITLE
I have added extensions xls,xlsx in rules but it still not work

### ISSUE THREAD

**Issue by waynezwf** [mohorev/yii2-upload-behavior#53]
I have added extensions xls,xlsx in rules but it still not work. When i upload a xlsx file it show me an extension name error.

**Comment by maxodrom** [comment]
@waynezwf  Try to use UploadBehavior but not UploadImageBehavior.

```php
    /**
     * @inheritdoc
     */
    function behaviors()
    {
        return [
            [
                'class' => UploadBehavior::class,
                'attribute' => 'file',
                'scenarios' => ['insert', 'update'],
                'path' => '@webroot/upload/docs/{category.id}',
                'url' => '@web/upload/docs/{category.id}',
            ],
        ];
    }
```

**Comment by waynezwf** [comment]
Thanks maxodrom so much. Yes I use the UploadBehavior, but it still show me an exception "extension name error". At last I add a rule 'checkExtensionByMimeType' => false in rules function.
