### ISSUE TITLE
Ability not to save the original image file

### ISSUE THREAD

**Issue by Matvik** [mohorev/yii2-upload-behavior#56]
Now there is no possibility not to store the original image file after generation of thumbbs. Can you add this option? thank you

**Comment by mohorev** [comment]
You can extend class of this behavior and write your custom logic.

**Comment by Matvik** [comment]
Made pull request which adds this functionality. 

Also removed strange if () block in UploadImageBehavior::init() function, that does not allow this function to be performed if createThumbsOnSave is false (and createThumbsOnRequest is true)

**Comment by mohorev** [comment]
Merged. New tag 0.2.1 created.

**Comment by Matvik** [comment]
Sorry, packagist is not updated automaticly. Perhaps webhook not works?

**Comment by mohorev** [comment]
@Matvik Done
