### ISSUE TITLE
Как удалить загруженное изображение без загрузки нового?

### ISSUE THREAD

**Issue by klipenko-stanislav** [mohorev/yii2-upload-behavior#61]
Допустим, требуется просто удалить загруженное изображение, без перезаписи новым. Например, для этого решено использовать boolean атрибут (чекбокс) "delete_image". Как это сделать?

**Comment by mohorev** [comment]
@klipenko-stanislav с помощью данного расширения - никак. Оно позволяет упростить загрузку изображения. Удаление должно быть реализовано самостоятельно.
