### ISSUE TITLE
Поведение не работает с табличным вводом?

### ISSUE THREAD

**Issue by EvgeniiZaets** [mohorev/yii2-upload-behavior#62]
Здравствуйте. Появилась необходимость обработки нескольких моделей одного вида в одной форме. Другими словами использовать табличный ввод.
В моем случае для каждой модели есть строковые поле загрузки файла вида:
`$form->field($model, "[$model->id]filename")->fileInput();`

Но поведение не обрабатывает такой кейс.
Аналогичная проблема упоминалась [здесь](https://github.com/mohorev/yii2-upload-behavior/issues/2)
Решение проблемы предложил maxxi165
"В общем, проблема в следующем. В beforeValidate() поведения файл для модели загружается строкой...
в случае, когда на странице несколько экземпляров модели с файлами, нужно загружать так:
`$this->file = UploadedFile::getInstance($model, "[$index]" . $this->attribute);`"

Оно действительно работает, если влезть в код библиотеки. Была мысль переопределить beforeValidate(), но я не могу этого сделать т.к. в нем идет обращение к приватному свойству $this->_file

Подскажите как можно решить данную проблему?

**Comment by mohorev** [comment]
@EvgeniiZaets никто так и не смог предложить красивое решение для множественной загрузки. А я с данным расширением уже давно не работаю.

Тем не менее постарался вам помочь, сделал file свойство protected. Это все что могу сделать быстро, не сломав логику поведения.

Выпустил новый релиз 0.2.2
